// Code generated by hardware/gui/sdlimgui/shaders/generate.go DO NOT EDIT

package shaders

const Cursor int32 = 1
const DebugScr int32 = 1
const GUI int32 = 0
const NoCursor int32 = 0
const Overlay int32 = 2
const PlayScr int32 = 3
const PrefsCRT int32 = 4
