linters:
  disable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
  enable:
    - bodyclose
    - unconvert
    - misspell
    - whitespace
    - unparam
    - scopelint
    - gocritic
  fast: false

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - exitAfterDefer

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
