// Pacakge future conceptualises event delays inside the VCS. An event in this
// context means something that occurs as a response to a stimulus generated by
// the CPU. For example, the ROM program cause the CPU to strobe the RESP0
// address. From the moment the address is written to the act of resetting the
// player's horizontal position does not happen immediately. Instead there is a
// short delay, measured in cycles, before the effect of the memory write
// occurs.
//
// The emulation code is full of events, like RESP0, that from the viewpoint of
// the event itself occur in the future. In the future package we use the Event
// type to represent this. The Event type is not instantiated directly.
// Instead, events are scheduled via an instance of the Ticker type.
//
// The Ticker type coordinates scheduled events for those parts of the VCS that
// experience stimulus delays, for instance each player sprite has an instance
// of Ticker. Events are created and registered with Schedule function.  The
// function takes the delay period, a label (useful identifying the event for
// debuggers) and a callback function as an argument. The callback is called
// once the delay period has expired.
//
// The Tick() function of the Ticker type is used to indicate time has passed.
// The RemainingCycles() function indicates how much more time (or to put
// another way, how many more call to Tick()) are required before the payload
// is executed. It is up to the users of the package to govern how often and
// when Tick() is called. The other Ticker type functions help the governor to
// fine tune the ticks.
//
// To help keep code clean, two interfaces to the Ticker type are provided, the
// Scheduler and Observer. The Scheduler is used in those places where an event
// is only ever scheduled. The Observer interface meanwhile is useful for
// debuggers.
package future
