package console

// Style specifies the printing mode
type Style int

// enumeration of print styles
const (
	// disassembly output at cpu cycle boundaries
	StyleCPUStep Style = iota

	// disassembly output at video cycle boundaries
	StyleVideoStep

	// information about the machine
	StyleInstrument

	// information about the emulator, rather than the emulated machine
	StyleEmulatorInfo

	// the input prompt
	StylePrompt
	StylePromptAlt
	StylePromptConfirm

	// non-error information from a command
	StyleFeedback

	// help information
	StyleHelp

	// user input (not used by all user interface types [eg. echoing terminals])
	StyleInput

	// information as a result of an error. errors can be generated by the
	// emulation or the debugger
	StyleError
)

// IncludeInScriptOutput returns true if print styles is to be included in the
// output of a script recording
func (sty Style) IncludeInScriptOutput() bool {
	switch sty {
	case StyleError, StyleInput, StylePrompt:
		return false
	default:
		return true
	}
}
