// This file is part of Gopher2600.
//
// Gopher2600 is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Gopher2600 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Gopher2600.  If not, see <https://www.gnu.org/licenses/>.

package moviecart

import (
	_ "embed"
)

// coreData is the binary file generated by the moviecart project
// https://github.com/lodefmode/moviecart/tree/main/asm

//go:embed "core.bin"
var coreData []byte

// key addresses in the core program. data at these address or just after in
// the case of JMP instructions, will be altered during playback.
//
// these *must* relate to the core.bin embedded above
//
// !!TODO: embed core.bin address constants, generated during the assembly process of core.bin
const (
	// processAddress().
	addrTitleLoop = 0xb50

	// fillAddrRightLine().
	addrSetAudRight = 0x948
	addrSetGData5   = 0x958
	addrSetGData6   = 0x950
	addrSetGData7   = 0x968
	addrSetGData8   = 0x960
	addrSetGData9   = 0x94a
	addrSetGCol5    = 0x95c
	addrSetGCol6    = 0x954
	addrSetGCol7    = 0x964
	addrSetGCol8    = 0x96c
	addrSetGCol9    = 0x94e
	addrSetBkColR   = 0x976
	addrSetPfColR   = 0x97c

	// fillAddrLeftLine().
	addrSetAudLeft   = 0x986
	addrSetGData0    = 0x992
	addrSetGData1    = 0x982
	addrSetGData2    = 0x9a2
	addrSetGData3    = 0x99a
	addrSetGData4    = 0x98a
	addrSetGCol0     = 0x996
	addrSetGCol1     = 0x98e
	addrSetGCol2     = 0x99e
	addrSetGCol3     = 0x9a6
	addrSetGCol4     = 0x98c
	addrPickContinue = 0x9ba
	addrRightLine    = 0x944
	addrEndLines     = 0xa80
	addrSetBkColL    = 0x9b4
	addrSetPfColL    = 0x9b8

	// fillAddrEndLines().
	addrSetAudEndlines     = 0xa8c
	addrSetOverscanSize    = 0xa9c
	addrSetVBlankSize      = 0xab2
	addrPickExtraLines     = 0xabb // what's this
	addrPickTransport      = 0xac8
	addrTransportDirection = 0x880
	addrTransportButtons   = 0x896

	// fillAddrBlankLines().
	addrAudioBank = 0xb80
)
